version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - src/config/.env
    depends_on:
      - db_postgres
    restart: always

  db_postgres:
    image: "postgres:alpine"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - src/config/.env
    restart: always
